/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client2;

import java.io.File;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;

/**
 *
 * @author Krzysiek
 */
public class ClientGUI extends javax.swing.JFrame{
    private String currentLocalDir;
    private Client2 client;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI(){
        this.client = new Client2();
        
        this.currentLocalDir = System.getProperty("user.dir");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        localTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        serverTree = new javax.swing.JTree();
        ButtonStor = new javax.swing.JButton();
        ButtonRetr = new javax.swing.JButton();
        TextFieldIP = new javax.swing.JTextField();
        labelIP = new javax.swing.JLabel();
        ButtonConnect = new javax.swing.JButton();
        labelServer = new javax.swing.JLabel();
        ButtonDele = new javax.swing.JButton();
        ButtonRmd = new javax.swing.JButton();
        ButtonMkd = new javax.swing.JButton();
        labelUser = new javax.swing.JLabel();
        TextFieldUser = new javax.swing.JTextField();
        labelPass = new javax.swing.JLabel();
        TextFieldPassword = new javax.swing.JPasswordField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Partial Commander");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        localTree.setModel(new ClientTreeModel(currentLocalDir));
        jScrollPane1.setViewportView(localTree);

        serverTree.setModel(null);
        jScrollPane2.setViewportView(serverTree);

        ButtonStor.setText(">>");
        ButtonStor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStorActionPerformed(evt);
            }
        });

        ButtonRetr.setText("<<");
        ButtonRetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetrActionPerformed(evt);
            }
        });

        TextFieldIP.setText("127.0.0.1");
        TextFieldIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIPActionPerformed(evt);
            }
        });

        labelIP.setText("IP:");

        ButtonConnect.setText("Connect");
        ButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConnectActionPerformed(evt);
            }
        });

        labelServer.setText("Server actions:");

        ButtonDele.setText("Delete File");

        ButtonRmd.setText("Delete Directory");

        ButtonMkd.setText("Create Directory");

        labelUser.setText("User:");

        labelPass.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonStor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonRetr))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelServer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ButtonDele))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonRmd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonMkd))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelIP)
                        .addGap(3, 3, 3)
                        .addComponent(TextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonConnect)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIP)
                    .addComponent(ButtonConnect)
                    .addComponent(labelUser)
                    .addComponent(TextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPass)
                    .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ButtonStor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetr)
                        .addGap(19, 19, 19)
                        .addComponent(labelServer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRmd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonMkd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIPActionPerformed

    private void ButtonStorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStorActionPerformed
        TreePath localPath = localTree.getSelectionPath();
        System.out.println(localPath.toString());
        String[] localPathArray = localPath.toString().replaceAll("[\\[\\]]", "").split(", ");
        TreePath serverPath = serverTree.getSelectionPath();
        System.out.println(serverPath.toString());
        String[] serverPathArray = serverPath.toString().replaceAll("[\\[\\]]", "").split(", ");
        if(client.isLogged()){
            String relativeLocalDir = File.separator + "";
            String relativeServerDir = File.separator + "";
            for(int i=1; i < localPathArray.length-1 ; i++){
                relativeLocalDir += localPathArray[i] + File.separator;
            }
            String fileName = localPathArray[localPathArray.length-1];
            for(int i=1; i < serverPathArray.length-1 ; i++){
                relativeServerDir += serverPathArray[i] + File.separator;
            }
            try {
                String originalUserDir = System.setProperty("user.dir", currentLocalDir + relativeLocalDir);
                client.changeDirectory(relativeServerDir);
                client.putFile(currentLocalDir + relativeLocalDir, fileName);
                client.changeDirectory("/");
                // TODO: put to selected folder
                System.setProperty("user.dir", originalUserDir);
            } catch (IOException ex) {
                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileTransferFailedException ex) {
                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Błąd przesyłania pliku", "Błąd pliku", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            
        }
    }//GEN-LAST:event_ButtonStorActionPerformed

    private void ButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConnectActionPerformed
        try {
            client.connect(TextFieldIP.getText());
            System.out.println(TextFieldPassword.getPassword());
            client.login(TextFieldUser.getText(), TextFieldPassword.getText());
            serverTree.setModel(new ServerTreeModel(client));
            jScrollPane2.setViewportView(serverTree);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonConnectActionPerformed

    private void ButtonRetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetrActionPerformed
        TreePath path = serverTree.getSelectionPath();
        System.out.println(path.toString());
    }//GEN-LAST:event_ButtonRetrActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            client.quit();
            System.out.println(client.getResponse());
        } catch (IOException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run(){
                new ClientGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConnect;
    private javax.swing.JButton ButtonDele;
    private javax.swing.JButton ButtonMkd;
    private javax.swing.JButton ButtonRetr;
    private javax.swing.JButton ButtonRmd;
    private javax.swing.JButton ButtonStor;
    private javax.swing.JTextField TextFieldIP;
    private javax.swing.JPasswordField TextFieldPassword;
    private javax.swing.JTextField TextFieldUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelServer;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTree localTree;
    private javax.swing.JTree serverTree;
    // End of variables declaration//GEN-END:variables
}
